/*
 * DEPARTMENTS 테이블과 LOCATIONS 테이블을 사용하여 각 부서가 어느 지역에 위치하는지 찾기
 */
SELECT D.DEPARTMENT_ID
     , D.DEPARTMENT_NAME 
     , D.LOCATION_ID 
     , L.LOCATION_ID 
     , L.CITY
     , L.COUNTRY_ID 
  FROM DEPARTMENTS D
  JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID
 ORDER BY D.DEPARTMENT_ID;

/*
 * 지역별로 몇개의 부서가 배치 되었는지 확인
 * 단, MANAGER_ID 가 NULL 인 부서는 제외
 */
SELECT COUNT(*) AS 부서수
     , L.LOCATION_ID
     , L.STREET_ADDRESS
     , L.POSTAL_CODE
     , L.CITY
     , L.STATE_PROVINCE
  FROM DEPARTMENTS D
  JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID
 WHERE D.MANAGER_ID IS NOT NULL
 GROUP BY L.LOCATION_ID
     , L.STREET_ADDRESS
     , L.POSTAL_CODE
     , L.CITY
     , L.STATE_PROVINCE;
--L.LOCATION_ID 가 PK(식별자)이기 때문에 이것만 그룹핑해도 상관 없음. (대신 출력도 LOCATION_ID 만 가능)

    
/*
 * 지역별 사원수가 얼마나 되는지 찾기
 */
SELECT COUNT(*) AS 사원수
     , L.LOCATION_ID
     , L.STREET_ADDRESS
     , L.POSTAL_CODE
     , L.CITY
     , L.STATE_PROVINCE
  FROM EMPLOYEES E
  JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
  JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID
 WHERE D.MANAGER_ID IS NOT NULL
 GROUP BY L.LOCATION_ID 
     , L.STREET_ADDRESS
     , L.POSTAL_CODE
     , L.CITY
     , L.STATE_PROVINCE;
    

