/*
 * EMPLOYEES 의 HIRE_DATE 열의 값을 +10 년 하여 수정한다.
 */
/*내풀이
UPDATE EMPLOYEES 
   SET HIRE_DATE = HIRE_DATE + INTERVAL '10' YEAR;
SELECT * FROM EMPLOYEES; */
UPDATE EMPLOYEES
   SET HIRE_DATE = ADD_MONTHS(HIRE_DATE, 120);
/*
 * LOCATIONS 테이블에 학원 주소 정보를 추가하세요.
 */
/*내풀이
INSERT INTO LOCATIONS (LOCATION_ID, STREET_ADDRESS, CITY) 
       VALUES (3300, '테헤란로 14길6', '서울특별시');
SELECT * FROM LOCATIONS;
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'LOCATIONS';
SELECT * FROM USER_CONS_COLUMNS WHERE TALBE_NAME = 'LOCATIONS';*/
INSERT INTO COUNTRIES VALUES('KR', 'Korea', 3);
INSERT INTO LOCATIONS VALUES(
       (SELECT MAX(LOCATION_ID) + 100 FROM LOCATIONS)
     , '테헤란로14길 6'
     , '06234'
     , '강남구'
     , '서울시'
     , 'KR'  --> COUNTRIES TABLE 참조. 따라서 부모 테이블 COUNTRIES 에 데이터 추가해놔야 오류 없음 
     );
SELECT * FROM LOCATIONS L 
  JOIN COUNTRIES C ON L.COUNTRY_ID = C.COUNTRY_ID
 WHERE L.COUNTRY_ID = 'KR';  --데이터 추가 확인용 SELECT 구문
/*
 * DEPARTMENTS의 IT 부서에 대한 LOCATION_ID 를 학원 주소로 수정하세요.
 */
UPDATE DEPARTMENTS
   SET LOCATION_ID = 3300
 WHERE DEPARTMENT_NAME = 'IT';

SELECT * FROM DEPARTMENTS;
/*
 * EMPLOYEES 에서 COMMISSION_PCT 가 NULL 인 경우 0으로 수정하세요.
 */
UPDATE EMPLOYEES
   SET COMMISSION_PCT = 0
 WHERE COMMISSION_PCT IS NULL;

SELECT * FROM EMPLOYEES;
/*
 * EMPLOYEES 에서 MANAGER_ID 가 NULL 인 사원은 DEPARTMENTS 테이블의 MANAGER_ID 로
 * 수정하세요. 
 */
SELECT * FROM EMPLOYEES WHERE MANAGER_ID IS NULL;
UPDATE EMPLOYEES E
   SET E.MANAGER_ID = (SELECT D.MANAGER_ID 
                         FROM DEPARTMENTS D 
                        WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID)
 WHERE E.MANAGER_ID IS NULL;

SELECT * FROM EMPLOYEES;
/*
 * EMPLOYEES 에서 DEPARTMENT_ID 가 NULL 인 사원은 MANAGER_ID 의 값을 활용하여 해당 MANAGER_ID 와
 * 동일한 DEPARTMENT_ID 값을 가지도록 수정하세요.
 * (MANAGER_ID 는 EMPLOYEE_ID 와 외래키 관계입니다.)
 */
UPDATE EMPLOYEES E1
   SET DEPARTMENT_ID = (SELECT DEPARTMENT_ID
                          FROM EMPLOYEES E2
                         WHERE EMPLOYEE_ID = E1.MANAGER_ID)
 WHERE DEPARTMENT_ID IS NULL;

SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IS NULL;
SELECT * FROM EMPLOYEES;
/*
 * DEPARTMENTS 에서 MANAGER_ID 가 NULL 인 데이터는 삭제하세요.
 */
DELETE FROM DEPARTMENTS WHERE MANAGER_ID IS NULL;
SELECT * FROM DEPARTMENTS;
/*
 * JOBS 테이블과 동일한 구조의 KJOBS 테이블을 만들고 JOB_TITLE 열의 값을
 * 한글로 번역하여 수정한다.
 * 단, MIN_SALARY, MAX_SALARY 컬럼은 만들 필요 없음.
 */
CREATE TABLE KJOBS(
       JOB_ID VARCHAR2(10) PRIMARY KEY
      ,JOB_TITLE VARCHAR2(35) 
);
INSERT INTO KJOBS(SELECT JOB_ID, JOB_TITLE FROM JOBS);
SELECT * FROM KJOBS;
UPDATE KJOBS SET JOB_TITLE = '회장' WHERE JOB_TITLE = 'President';
UPDATE KJOBS SET JOB_TITLE = '행정부 부총재' WHERE JOB_TITLE = 'Administration Vice President';
UPDATE KJOBS SET JOB_TITLE = '관리 관리자' WHERE JOB_TITLE = 'Administration Assistant';
UPDATE KJOBS SET JOB_TITLE = '재무 관리자' WHERE JOB_TITLE = 'Finance Manager';
UPDATE KJOBS SET JOB_TITLE = '회계사' WHERE JOB_TITLE = 'Accountant';
UPDATE KJOBS SET JOB_TITLE = '회계 관리자' WHERE JOB_TITLE = 'Accounting Manager';
UPDATE KJOBS SET JOB_TITLE = '공인회계사' WHERE JOB_TITLE = 'Public Accountant';
UPDATE KJOBS SET JOB_TITLE = '판매 관리자' WHERE JOB_TITLE = 'Sales Manager';
UPDATE KJOBS SET JOB_TITLE = '판매 담당자' WHERE JOB_TITLE = 'Sales Representative';
UPDATE KJOBS SET JOB_TITLE = '구매 관리자' WHERE JOB_TITLE = 'Purchasing Manager';
UPDATE KJOBS SET JOB_TITLE = '구매 담당자' WHERE JOB_TITLE = 'Purchasing Clerk';
UPDATE KJOBS SET JOB_TITLE = '재고 관리자' WHERE JOB_TITLE = 'Stock Manager';
UPDATE KJOBS SET JOB_TITLE = '재고 담당자' WHERE JOB_TITLE = 'Stock Clerk';
UPDATE KJOBS SET JOB_TITLE = '배송 담당자' WHERE JOB_TITLE = 'Shipping Clerk';
UPDATE KJOBS SET JOB_TITLE = '프로그래머' WHERE JOB_TITLE = 'Programmer';
UPDATE KJOBS SET JOB_TITLE = '마케팅 관리자' WHERE JOB_TITLE = 'Marketing Manager';
UPDATE KJOBS SET JOB_TITLE = '마케팅 담당자' WHERE JOB_TITLE = 'Marketing Representative';
UPDATE KJOBS SET JOB_TITLE = '인사 담당자' WHERE JOB_TITLE = 'Human Resources Representative';
UPDATE KJOBS SET JOB_TITLE = '홍보 담당자' WHERE JOB_TITLE = 'Public Relations Representative';
/*
 * DEPARTMENTS 테이블에 DEPARMENT_NAME_KR 컬럼을 추가 후 DEPARTMENT_NAME 을
 * 한글로 변역한 데이터가 수정되게 한다.
 */
SELECT * FROM DEPARTMENTS;
ALTER TABLE DEPARTMENTS ADD DEPARTMENT_NAME_KR VARCHAR2(20);
UPDATE DEPARTMENTS SET DEPARTMENT_NAME_KR = '관리부' WHERE DEPARTMENT_ID = 10;
UPDATE DEPARTMENTS SET DEPARTMENT_NAME_KR = '마케팅' WHERE DEPARTMENT_ID = 20;
UPDATE DEPARTMENTS SET DEPARTMENT_NAME_KR = '구매팀' WHERE DEPARTMENT_ID = 30;
UPDATE DEPARTMENTS SET DEPARTMENT_NAME_KR = '인사팀' WHERE DEPARTMENT_ID = 40;
UPDATE DEPARTMENTS SET DEPARTMENT_NAME_KR = '배송팀' WHERE DEPARTMENT_ID = 50;
UPDATE DEPARTMENTS SET DEPARTMENT_NAME_KR = '아이티' WHERE DEPARTMENT_ID = 60;
UPDATE DEPARTMENTS SET DEPARTMENT_NAME_KR = '홍보팀' WHERE DEPARTMENT_ID = 70;
UPDATE DEPARTMENTS SET DEPARTMENT_NAME_KR = '판매팀' WHERE DEPARTMENT_ID = 80;
UPDATE DEPARTMENTS SET DEPARTMENT_NAME_KR = '경영팀' WHERE DEPARTMENT_ID = 90;
UPDATE DEPARTMENTS SET DEPARTMENT_NAME_KR = '자금팀' WHERE DEPARTMENT_ID = 100;
UPDATE DEPARTMENTS SET DEPARTMENT_NAME_KR = '회계팀' WHERE DEPARTMENT_ID = 110;
/*
 * KJOBS 테이블에 한글로 번역한 직무 타이틀을 JOBS 테이블에 JOB_TITLE_KR 컬럼을
 * 추가후 수정이 되도록 한다.(DEPARTMENTS 테이블 처럼 하나의 테이블에 영문/한글이
 * 모두 들어가게 한다.) 모든 작업을 완료 후 KJOBS 테이블은 제거 한다.
 */
ALTER TABLE JOBS ADD JOB_TITLE_KR VARCHAR2(20);
UPDATE JOBS 
   SET JOB_TITLE_KR = (SELECT JOB_TITLE FROM KJOBS WHERE JOB_ID = JOBS.JOB_ID);
SELECT * FROM JOBS;
DROP TABLE KJOBS;
/*
 * JOBS 테이블에 다음의 데이터를 추가 한다.(JOB_TITLE_KR 도 추가되어 있어야 함)
 *     JOB_ID    JOB_TITLE           MIN_SALARY    MAX_SALARY
 *     IT_ITRN   Intern Programmer   3200          3800
 *     SV_MGR    Server Manager      4000          10000
 *     SV_ENG    Server Engineer     6000          12000
 *     NT_MGR    Network Manager     5000          11000
 *     NT_ENG    Network Engineer    7000          13000
 */
INSERT INTO JOBS(JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY)
          VALUES(IT_ITRN, Intern Programmer, 3200, 3800);
INSERT INTO JOBS(JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY)
          VALUES(SV_MGR, Server Manager, 4000, 10000);
INSERT INTO JOBS(JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY)
          VALUES(SV_ENG, Server Engineer, 6000, 12000);
INSERT INTO JOBS(JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY)
          VALUES(NT_MGR, Network Manager, 5000, 11000);
INSERT INTO JOBS(JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY)
          VALUES(NT_ENG, Network Engineer, 7000, 13000);
SELECT * FROM JOBS;
/*
 * DEPARTMENTS 테이블에 다음의 데이터를 추가 한다.(DEPARTMENT_NAME_KR 도 추가되어 있어야 함)
 *     DEPARTMENT_ID    DEPARTMENT_NAME    MANAGER_ID    LOCATION_ID
 *     280              Server             NULL          (학원주소에 해당하는 ID)
 *     290              Network            NULL          (학원주소에 해당하는 ID)
 */
INSERT INTO DEPARTMENTS(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
              VALUES(280, 'Server', NULL, (SELECT LOCATION_ID FROM LOCATIONS WHERE STREET_ADDRESS = '테헤란로14길 6'));
INSERT INTO DEPARTMENTS(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
              VALUES(290, 'Network', NULL, (SELECT LOCATION_ID FROM LOCATIONS WHERE STREET_ADDRESS = '테헤란로14길 6'));
SELECT * FROM DEPARTMENTS;             
/*
 * 새로 신설된 Server, Network 부서를 위한 인력을 충원하고 있는 것으로 가정하여 각 부서마다
 * 3명의 인원을 EMPLOYEES 에 추가한다.(Manager 직무 1명, Engineer 직무 2명)
 *     - 초기에 모든 인원은 JOBS 테이블의 MIN_SALARY 의 급여를 받는 것으로 한다.
 *     - Server, Network 부서에 인원을 추가 할 때 반드시 1명의 부서장이 필요하기 때문에 인원 중 1명을
 *       부서장으로 만든다.(DEPARTMENTS 테이블의 MANAGER_ID 를 설정한다.)
 *     - 부서장으로 선택된 인원은 JOBS 테이블의 MIN_SALARY 급여에서 +2000 상승된 급여로 받을 수 있게
 *       데이터를 수정한다.
 */

/*
 * 모든 급여 정보를 수정하려고 한다.
 * JOBS 테이블과 EMPLOYEES 테이블의 모든 급여 정보를 기존보다 5% ~ 10% 상승 시키도록 한다.
 *     - 급여가 4000 미만인 경우 10% 상승
 *     - 급여가 4000 이상 8000 미만인 경우 8% 상승
 *     - 급여가 8000 이상 12000 미만인 경우 6% 상승
 *     - 급여가 12000 이상인 경우 5% 상승
 *     - 정수 1번째 자리에서 절삭할 것. 예) 4333.333 은 4330 으로 절삭.
 */
SELECT SALARY FROM EMPLOYEES;

UPDATE EMPLOYEES
   SET SALARY = CASE WHEN SALALY < 4000 THEN SALARY * 0.1
                     WHEN
                     WHEN
                     ELSE
                END     
   	               
   