/*
 * 집합 연산자
 *    - 2개 이상의 Record Set 결과를 하나의 Record Set 결과로 만드는 연산자
 *    - UNION, UNION ALL, INTERSECT, MINUS 연산자가 있다.
 * 
 * UNION
 *    - 합집합
 *    - 중복 안됨 -> 중복된 결과는 하나만 반영함
 * 
 * UNION ALL
 *    - 합집합
 *    - 중복 허용 -> 중복된 결과 까지 전부 반영됨
 * 
 * INTERSECT
 *    - 교집합
 * 
 * MINUS
 *    - 차집합
 */
SELECT *
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID IN (10, 20)
INTERSECT
SELECT *
  FROM EMPLOYEES
 WHERE MANAGER_ID = 101;

--1
SELECT DEPARTMENT_ID
     , NULL AS JOB_ID
     , COUNT(*)
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID IS NOT NULL
 GROUP BY DEPARTMENT_ID
UNION
SELECT NULL AS DEPARTMENT_ID
     , JOB_ID
     , COUNT(*)
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID IS NOT NULL
 GROUP BY JOB_ID
UNION
SELECT DEPARTMENT_ID
     , JOB_ID
     , COUNT(*)
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID IS NOT NULL
 GROUP BY DEPARTMENT_ID, JOB_ID;
 
-- 1과 2번 문은 같음

--2
SELECT DEPARTMENT_ID
     , JOB_ID
     , COUNT(*)
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID IS NOT NULL
 GROUP BY GROUPING SETS(DEPARTMENT_ID, JOB_ID, (DEPARTMENT_ID, JOB_ID));