CREATE TABLE REQ_ACCOUNTS(
	   ID NUMBER PRIMARY KEY
	 , NICKNAME VARCHAR2(35) UNIQUE
	 , EMAIL VARCHAR2(100) UNIQUE
	 , ISALLOW CHAR(1) DEFAULT('N') CHECK (ISALLOW IN ('N', 'Y'))
	 , REQDATE DATE DEFAULT(SYSDATE)
);

CREATE SEQUENCE SEQ_REQ_ACCOUNTS NOCACHE;

CREATE TABLE ACCOUNTS(
	   ID NUMBER PRIMARY KEY
	 , NICKNAME VARCHAR2(35) UNIQUE
	 , EMAIL VARCHAR2(100) UNIQUE
	 , PASSWORD VARCHAR2(100) NOT NULL
	 , LOGINDATE DATE NOT NULL
);

CREATE TABLE ACCOUNTS_ACCESS_LOG(
	   ID NUMBER PRIMARY KEY
	 , AID NUMBER REFERENCES ACCOUNTS(ID)
	 , LOGTYPE VARCHAR2(8) CHECK (LOGTYPE IN ('LOGIN', 'LOGOUT'))
	 , LOGDATE DATE DEFAULT(SYSDATE)
);

CREATE SEQUENCE SEQ_ACCOUNTS_ACCESS_LOG NOCACHE;

--회원가입 위한 요청 SQL 구문
INSERT INTO REQ_ACCOUNTS(ID, NICKNAME, EMAIL) 
       VALUES(SEQ_REQ_ACCOUNTS.NEXTVAL, 'yoon', 'yoon@gmail.com');
INSERT INTO REQ_ACCOUNTS(ID, NICKNAME, EMAIL) 
       VALUES(SEQ_REQ_ACCOUNTS.NEXTVAL, 'ji', 'ji@gmail.com');
INSERT INTO REQ_ACCOUNTS(ID, NICKNAME, EMAIL) 
       VALUES(SEQ_REQ_ACCOUNTS.NEXTVAL, 'seo', 'seo@gmail.com');
      
SELECT * FROM REQ_ACCOUNTS;

--회원 가입 요청을 승낙하기 위한 SQL 구문
UPDATE REQ_ACCOUNTS
   SET ISALLOW = 'Y'
 WHERE REQDATE BETWEEN TO_DATE('20221128') AND TO_DATE('20221201')
   AND ISALLOW = 'N';
  
INSERT INTO ACCOUNTS(
	SELECT SEQ_ACCOUNTS.NEXTVAL
	     , NICKNAME
	     , EMAIL
	     , 'temppassword'
	     , SYSDATE
	  FROM REQ_ACCOUNTS
	 WHERE ISALLOW = 'Y'
);
