CREATE TABLE T1(
       ID NUMBER PRIMARY KEY
     , NAME VARCHAR2(10)
     , DTYPE CHAR(1)
     , CNT NUMBER
);

CREATE TABLE T2(
       NAME VARCHAR2(10) PRIMARY KEY
     , CNT NUMBER
);

CREATE SEQUENCE SEQ_T1 NOCACHE; --시퀀스는 롤백 안먹힘.

DECLARE
	VNAME VARCHAR2(10);
	VDTYPE CHAR(1);
	VCNT NUMBER;
	EXISTS_NAME NUMBER;
BEGIN
	VNAME := :이름;
	VDTYPE := :타입;
	VCNT := :수량;
	
    INSERT INTO T1 VALUES(SEQ_T1.NEXTVAL, VNAME, VDTYPE, VCNT);

	SELECT COUNT(*)
	  INTO EXISTS_NAME
	  FROM T2
	 WHERE NAME = VNAME;
	
	IF(EXISTS_NAME = 0) THEN
	    INSERT INTO T2 VALUES(VNAME, VCNT);
	ELSE
		IF(VDTYPE = 'I') THEN
	    	UPDATE T2
	       	   SET CNT = CNT + VCNT
	     	 WHERE NAME = VNAME;
	    ELSIF(VDTYPE = 'O') THEN
	        UPDATE T2
	       	   SET CNT = CNT - VCNT
	     	 WHERE NAME = VNAME;
	    ELSE
	    	DBMS_OUTPUT.PUT_LINE('롤백 합니다!!');
	        ROLLBACK;  --INSERT 에서 I,O 이외의 모든 값을 다 받음. 그래서 IF문에서 I,O 아니면 롤백실행
	    END IF;
	END IF;
	DBMS_OUTPUT.PUT_LINE('커밋 합니다!!');
    COMMIT;
END;

SELECT * FROM T1;
SELECT * FROM T2;