CREATE TABLE VISIT_T(
	context VARCHAR2(500 CHAR)
   ,nickname VARCHAR2(25 CHAR)
);

SELECT * FROM VISIT_T;

INSERT INTO VISIT_T VALUES('context', 'nickname');

DROP TABLE BOOKMARK_T;

CREATE TABLE BOOKMARK_T(
	id NUMBER PRIMARY KEY
   ,url VARCHAR2(100 CHAR)
   ,name VARCHAR2(100 CHAR)	
);

SELECT * FROM BOOKMARK_T;


INSERT INTO BOOKMARK_T VALUES(1, 'https://naver.com', '네이버');
INSERT INTO BOOKMARK_T VALUES(2, 'https://google.com', '구글');
INSERT INTO BOOKMARK_T VALUES(3, 'https://nate.com', '네이트');