CREATE TABLE VISIT_T(
    id NUMBER PRIMARY KEY
   ,nickname VARCHAR2(25 CHAR)
   ,context VARCHAR2(500 CHAR)
);

SELECT * FROM VISIT_T;

CREATE SEQUENCE VISIT_S;

SELECT VISIT_S.NEXTVAL FROM DUAL;

INSERT INTO VISIT_T VALUES('context', 'nickname');

DELETE FROM VISIT_T;
DROP TABLE VISIT_T;

DROP TABLE BOOKMARK_T;

CREATE TABLE BOOKMARK_T(
	id NUMBER PRIMARY KEY
   ,url VARCHAR2(100 CHAR)
   ,name VARCHAR2(100 CHAR)	
);

SELECT * FROM BOOKMARK_T;

CREATE SEQUENCE BOOKMARK_S;

INSERT INTO BOOKMARK_T VALUES(1, 'https://naver.com', '네이버');
INSERT INTO BOOKMARK_T VALUES(2, 'https://google.com', '구글');
INSERT INTO BOOKMARK_T VALUES(3, 'https://nate.com', '네이트');

SELECT BOOKMARK_S.NEXTVAL FROM DUAL;

DELETE FROM BOOKMARK_T;

drop sequence VISIT_S;
drop sequence bookmark_s;

CREATE TABLE USER_T(
	USERID VARCHAR2(20) PRIMARY KEY
  , PASSWORD VARCHAR2(20) NOT NULL
  , EMAIL VARCHAR2(100)
);

SELECT * FROM USER_T;
